#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hiredis
Version  : 1.0.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/9e/e0/c160dbdff032ffe68e4b3c576cba3db22d8ceffc9513ae63368296d1bcc8/hiredis-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/9e/e0/c160dbdff032ffe68e4b3c576cba3db22d8ceffc9513ae63368296d1bcc8/hiredis-1.0.0.tar.gz
Summary  : Minimalistic C client library for Redis
Group    : Development/Tools
License  : BSD-3-Clause
Requires: hiredis-license = %{version}-%{release}
Requires: hiredis-python = %{version}-%{release}
Requires: hiredis-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# hiredis-py
[![Build Status](https://travis-ci.org/redis/hiredis-py.svg?branch=master)](https://travis-ci.org/redis/hiredis-py)
[![Windows Build Status](https://ci.appveyor.com/api/projects/status/muso9gbe316tjsac/branch/master?svg=true)](https://ci.appveyor.com/project/duyue/hiredis-py/)

%package license
Summary: license components for the hiredis package.
Group: Default

%description license
license components for the hiredis package.


%package python
Summary: python components for the hiredis package.
Group: Default
Requires: hiredis-python3 = %{version}-%{release}

%description python
python components for the hiredis package.


%package python3
Summary: python3 components for the hiredis package.
Group: Default
Requires: python3-core

%description python3
python3 components for the hiredis package.


%prep
%setup -q -n hiredis-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550509903
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hiredis
cp vendor/hiredis/COPYING %{buildroot}/usr/share/package-licenses/hiredis/vendor_hiredis_COPYING
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hiredis/vendor_hiredis_COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
